name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    generator:
        runs-on: ubuntu-22.04
        name: Generator Unit Tests
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"
            - name: Install dependencies
              run: |
                python3 -m venv .venv
                source .venv/bin/activate
                pip3 install .
            - name: Run Tests
              run: |
                source .venv/bin/activate
                bash run_tests.sh
